/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        ctp: {
          base: "var(--base)",
          mantle: "var(--mantle)",
          crust: "var(--crust)",
          surface0: "var(--surface0)",
          surface1: "var(--surface1)",
          surface2: "var(--surface2)",
          "surface-slate": "var(--surface-slate)",
          overlay0: "var(--overlay0)",
          overlay1: "var(--overlay1)",
          overlay2: "var(--overlay2)",
          text: "var(--text)",
          subtext0: "var(--subtext0)",
          subtext1: "var(--subtext1)",
          accent: "var(--accent)",
          "accent-soft": "var(--accent-soft)",
          "accent-strong": "var(--accent-strong)",
          border: "var(--border)",
          red: "var(--red)",
          green: "var(--green)",
          yellow: "var(--yellow)",
          orange: "var(--orange)",
          blue: "var(--blue)",
          pink: "var(--pink)",
          teal: "var(--teal)",
        },
        node: {
          domain: "var(--c-domain)",
          skill: "var(--c-skill)",
          project: "var(--c-project)",
          task: "var(--c-task)",
          person: "var(--c-person)",
          tag: "var(--c-tag)",
          routine: "var(--c-routine)",
        },
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};
